### ISSUE TITLE
Cookie expiration period

### ISSUE THREAD

**Issue by binary-data** [mac-cain13/xdebug-helper-for-chrome#59]
Hello.

Xdebug helper works fine, but there is one issue that bothers me often. It seems that expiration time of cookie is hardcoded to 24 hours, and it expires at inappropriate moments. It is easy to forget about it, renew page over and over and wonder why breakpoints doesn't work :)

Maybe there should be some option to set cookie expiration time?

**Comment by mac-cain13** [comment]
To what time would you set this option if we have it? Maybe that is a nice new default to use... 

I don't really feel for adding options when a sane default will do. Maybe making it longer or shorter will already solve this problem. What do you think?

**Comment by binary-data** [comment]
It will be good for me that it will never expire :) so I could control when to turn debugging on and off. If debugging state was set manually, I expect it to be the same until I explicitely set another. Or just set it as long as possible, like a week.

But that is only my opinion and my workflow.

**Comment by mac-cain13** [comment]
I think it could be a nice update to set the cookie expiration time to a year. Then you always need to disable debugging/tracing/whatever yourselves instead of depending on it to turn off after a certain time.

There probably aren't that much developers waiting for it to time out. So I think it's a nice change to switch to a year instead of a day.

**Comment by binary-data** [comment]
I certainly dont mind :+1:
